// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigDatabase  = "database"
	SourceConfigFoo       = "foo"
	SourceConfigNamespace = "namespace"
	SourceConfigPassword  = "password"
	SourceConfigScope     = "scope"
	SourceConfigUrl       = "url"
	SourceConfigUsername  = "username"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigDatabase: {
			Default:     "",
			Description: "Database is the database name for the SurrealDB server.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigFoo: {
			Default:     "",
			Description: "SourceConfigParam is named foo and must be provided by the user.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigNamespace: {
			Default:     "",
			Description: "Namespace is the namespace for the SurrealDB server.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigPassword: {
			Default:     "",
			Description: "Password is the password for the SurrealDB server.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigScope: {
			Default:     "",
			Description: "Scope is the scope for the SurrealDB server.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigUrl: {
			Default:     "",
			Description: "URL is the connection string for the SurrealDB server.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigUsername: {
			Default:     "",
			Description: "Username is the username for the SurrealDB server.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
